services:
  mysql:
    image: mysql:8.0
    container_name: travlog_mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: asdf
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d/migrations
      - ./data:/docker-entrypoint-initdb.d/data
      - ./init-scripts:/docker-entrypoint-initdb.d/init-scripts
    command: --default-authentication-plugin=mysql_native_password

