services:
  mysql:
    image: mysql:8.0
    container_name: travlog-mysql-container
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE_NAME}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d/migrations
      - ./data:/docker-entrypoint-initdb.d/data
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
    tmpfs:
      - /var/lib/mysql